# REQUISIÇÕES DE PRODUTOS

###
GET http://localhost:3000/produtos HTTP/1.1

###
GET http://localhost:3000/produtos/1 HTTP/1.1

###
POST http://localhost:3000/produtos HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsIm5vbWVVc3VhcmlvIjoidXN1YXJpbzEiLCJpYXQiOjE3NDk1MDI0OTUsImV4cCI6MTc0OTUwNjA5NX0.g4bIPRgAFxSRDDfOVK-urY8z1rWAXLx14dNlK2qDg3g

{
    "nome": "Maça",
    "preco": 1.99,
    "dataCriacao": "2023-10-01",
    "dataValidade": "2023-10-15"
}

### 
PATCH http://localhost:3000/produtos/6 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsIm5vbWVVc3VhcmlvIjoidXN1YXJpbzEiLCJpYXQiOjE3NDk1MDI0OTUsImV4cCI6MTc0OTUwNjA5NX0.g4bIPRgAFxSRDDfOVK-urY8z1rWAXLx14dNlK2qDg3g

{
    "preco": 3.99
}

### 
DELETE http://localhost:3000/produtos/5 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsIm5vbWVVc3VhcmlvIjoidXN1YXJpbzEiLCJpYXQiOjE3NDk1MDI0OTUsImV4cCI6MTc0OTUwNjA5NX0.g4bIPRgAFxSRDDfOVK-urY8z1rWAXLx14dNlK2qDg3g


# REQUISIÇÕES DE FAVORITOS

### Adicionar um produto aos favoritos, precisa estar autenticado como user
POST http://localhost:3000/favoritos/ID_DO_PRODUTO
Authorization: Bearer // Aqui vai o token

### Remove um produto dos favoritos, precisa estar autenticado como user
DELETE http://localhost:3000/favoritos/ID_DO_PRODUTO
Authorization: Bearer // Aqui vai o token

### Listar produtos favoritos, precisa estar autenticado como user
GET http://localhost:3000/favoritos
Authorization: Bearer // Aqui vai o token


# CADASTRO E AUTENTICAÇÃO   

### Registro de usuário
POST http://localhost:3000/auth/register HTTP/1.1
Content-Type: application/json

{
    "nomeUsuario": "usuario1",
    "nome": "Usuário Teste",
    "senha": "senha123",
    "email": "usuario1@email.com"
}

### Login de usuário
POST http://localhost:3000/auth/login HTTP/1.1  
Content-Type: application/json

{
    "nomeUsuario": "usuario1",
    "senha": "senha123"
}